# Generated by Django 4.1.7 on 2023-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('member', models.BooleanField(default=False)),
                ('select', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
    ]
