# Generated by Django 4.1.7 on 2023-09-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0002_alter_blog_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desc',
            new_name='concern',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='select',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='blog',
            name='member',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
