# Generated by Django 4.1.7 on 2023-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0005_signupdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
