# Generated by Django 4.1.7 on 2024-04-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0006_alter_signupdata_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteTechnologyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=30)),
                ('write', models.TextField(max_length=3000)),
                ('date', models.DateField()),
            ],
        ),
    ]
