# Generated by Django 4.1.7 on 2024-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0008_writeblockchainblog_writeroboticsblog_writewebblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeblockchainblog',
            name='topic',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='writeroboticsblog',
            name='topic',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='writetechnologyblog',
            name='topic',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='writewebblog',
            name='topic',
            field=models.CharField(max_length=150),
        ),
    ]
