# Generated by Django 4.1.7 on 2024-04-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0010_alter_writeblockchainblog_write_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('blog', models.TextField(max_length=10000)),
            ],
        ),
    ]
